### ISSUE TITLE
support for inner, outer  ts node

### ISSUE THREAD

**Issue by JoseConseco** [David-Kunz/treesitter-unit#10]
It would be cool if  we had support for inner and outer operator modifiers  support
eg.

-  for parameter - inner (select without comma), outer - with adjacent coma - like it is now
-  inner - would work on inside content of function, class, conditional statement etc. 

With that user could select in easier eg inside if this statement: 
![image](https://user-images.githubusercontent.com/13521338/133890801-30f8f577-92df-4191-a7f1-51dd25c731db.png)
Very cool plugin btw. 
Also maybe textsubobj-smart could be renamed to:  ['c']hunk,  ['s']ection, ['r']egion, or  something easier to [remember](https://www.thesaurus.com/browse/section) .  This way we could select   `*ir` (inside region)  or `*ar`  (around region)

**Comment by David-Kunz** [comment]
Hi @JoseConseco ,

Thank you for this interesting proposal! Unfortunately I want to be independent of the used programming language, i.e. I don't want to hard code language-specific things in my code.

Therefore, the only information I have is the node structure

```
node_11 Line1
  node_21 Line1
    node_31 Line2
    node_32 Line2
      node_41 Line3
      node_42 Line3
```

which makes it impossible to see where to find the main node your your select.

Note: The content of the `if` statement could also be in the same line, so we shouldn't use this information.

Best regards,
David
