### ISSUE TITLE
Highlighting syncs only on cursor move

### ISSUE THREAD

**Issue by kuator** [David-Kunz/treesitter-unit#11]
![Peek 2022-05-15 12-08](https://user-images.githubusercontent.com/25168308/168459621-c66d9c83-3075-428b-b191-ec399c3931be.gif)
The highlight doesn't sync if I `u`ndo the last deletion, I have to move the cursor to make highlighting sync

**Comment by David-Kunz** [comment]
That's true, at the moment the new highlight only is applied when the cursor moves. Let me see if I can fix that.

**Comment by David-Kunz** [comment]
Hmm, there doesn't seem to be a valid event for that, so it could only be achieved with some hacks which I'd rather not introduce.

**Comment by kuator** [comment]
That's unfortunate
