### ISSUE TITLE
 Add deleted unit or changed unit to register

### ISSUE THREAD

**Issue by duikboot** [David-Kunz/treesitter-unit#2]
Hi, thanks for your plugin, really love the simplicity.

I expected the deleted or changed unit to be added to the register though, which would make it even more useful for refactoring code.

Thanks again for the plugin

**Comment by David-Kunz** [comment]
Hi @duikboot ,

Thanks for this very nice first issue :)

Another user pointed out, that it makes more sense to have operator mode maps. This also solves the problem of missing registers.

Please add this mapping:
```
vim.api.nvim_set_keymap('o', 'x', ':<c-u>lua require"treesitter-unit".select()<CR>', {noremap=true})
```

which will enable also `dx`, `cx`, `yx`, ... and puts it in the register.

Thanks again and best regards,
David

**Comment by duikboot** [comment]
I was wondering about operator mode maps, this is a very elegant solution. Works like a charm. 

Thanks and best regards,

Arjen
