### ISSUE TITLE
Is it possible to preview the unit?

### ISSUE THREAD

**Issue by kuator** [David-Kunz/treesitter-unit#3]
Is it possible to preview the unit to be operated on? Like adding some highlight?

**Comment by David-Kunz** [comment]
Hi @kuator ,

Absolutely, you can first highlight it and then delete it.
Make sure to have this mapping:
```
vnoremap x :lua require"treesitter-unit".select()<CR>
```

Then press `vx`, followed by your operation (e.g. `d` or `c`).

Best regards,
David

**Comment by kuator** [comment]
Thank you, but I was thinking about something similar to `set cursorline` but for unit, like, the unit is always highlighted and the highlight gets automatically updated when I move cursor, so I can see what's about to be deleted or yanked or another operation.
That way I would be able to use it with operator-mode as well instead of visual mode.

**Comment by David-Kunz** [comment]
Ah, I see, that's an interesting suggestion, let me investigate.

**Comment by David-Kunz** [comment]
Hi @kuator,

I've just added a new feature to highlight the region:
```
:lua require"treesitter-unit".enable_highlighting()
```
See [here](https://github.com/David-Kunz/treesitter-unit/blob/main/README.md#select-treesitter-unit) for more information.

You can also see it in the demo gif.

Thanks for this suggestion and best regards,
David

**Comment by kuator** [comment]
Amazing! Thank you!
