### ISSUE TITLE
Difference between au and iu?

### ISSUE THREAD

**Issue by kuator** [David-Kunz/treesitter-unit#4]
What's the difference between `au` and `iu`? If, let's say, my cursor on `while`, no matter whether I delete with `dau` or `diu`, it removes the whole loop body

**Comment by David-Kunz** [comment]
Hi @kuator ,

There are two differences:
- `viu` will only select the node where your cursor is at the moment. `vau` will select the next node after your cursor. 
- `vau` will also select the surroundings

**Comment by kuator** [comment]
So, this behaviour applies only to visual mode? What about operator-pending mode?

**Comment by David-Kunz** [comment]
It also applies to operator-pending mode. I just used visual mode as an example.

**Comment by kuator** [comment]
Thank you for answering!
