### ISSUE TITLE
Visual mode mappings don't work if using <Cmd>

### ISSUE THREAD

**Issue by frangio** [David-Kunz/treesitter-unit#5]
Hey, awesome plugin.

I instinctively defined my mappings using `<Cmd>` as opposed to `:<C-u>`, but this seems to interfere with the plugin in visual mode somehow, because `viu` does not work. I don't believe using `<Cmd>` should be an issue.

```vim
xnoremap iu <Cmd>lua require"treesitter-unit".select()<CR>
xnoremap au <Cmd>lua require"treesitter-unit".select(true)<CR>
onoremap iu <Cmd>lua require"treesitter-unit".select()<CR>
onoremap au <Cmd>lua require"treesitter-unit".select(true)<CR>
```

**Comment by David-Kunz** [comment]
Hi @frangio ,

Thank you! I just tried it out, it works for me. 

Can you specify how it doesn't work? 

Thanks for clarification and best regards,
David

**Comment by uga-rosa** [comment]
I made the same mistake at first. It seems that to use this function in visual mode, you need to tell the current position. You can't even use `:<C-u>`.
Here's what you need to change.
```vim
xnoremap iu :lua require"treesitter-unit".select()<CR>
xnoremap au :lua require"treesitter-unit".select(true)<CR>
```
Since `omap` is for operators, it is involved in the behavior of ciu, etc.

**Comment by David-Kunz** [comment]
Hi @uga-rosa, Thanks for this hint!

@frangio, does this solve your problem?

**Comment by David-Kunz** [comment]
Hi @frangio ,

I'll close this issue, if you still have problems, please get back to me!

Best regards,
David
