### ISSUE TITLE
Even if I disable highlight, the previous highlight will remain.

### ISSUE THREAD

**Issue by uga-rosa** [David-Kunz/treesitter-unit#6]
![image](https://user-images.githubusercontent.com/82267684/130732532-02f88564-eb65-454f-87c2-3a19aa19eb09.png)

**Comment by David-Kunz** [comment]
Hi @uga-rosa ,

Thanks or reporting, I can reproduce this issue.

I will look into it!

Best regards,
David

**Comment by uga-rosa** [comment]
Other than here, it is very convenient and comfortable. Thank you very much.

**Comment by David-Kunz** [comment]
Hi @uga-rosa ,

Thank you! I just fixed the error, it should work now!

I also introduced `toggle_highlighting(higroup?)` for more convenient switching.

Thanks again for reporting and best regards,
David
