### ISSUE TITLE
Allow/deny list of unit types

### ISSUE THREAD

**Issue by ouuan** [David-Kunz/treesitter-unit#7]
Now when using this plugin, sometimes unexpected units are selected. It will be great if we can add some unit types in the deny list so that these types won't be selected by treesitter-unit.

**Comment by David-Kunz** [comment]
Hi @ouuan ,

Thanks for this suggestion. Can you give me an example?

Thanks and best regards,
David

**Comment by David-Kunz** [comment]
Hi @ouuan ,

I've implemented the feature. It's not yet documented as I want to see if it works for you first.

You can all 
```lua
require'treesitter-unit'.setup({ ignore_types = { 'function_call' } })
```
(or any other list of types) to ignore those when selecting nodes.

Does this work for you?

Best regards,
David

**Comment by ouuan** [comment]
Sorry, I misunderstood how this plugin works. I thought it found the smallest node, but it doesn't. It seems that this plugin finds the largest node that starts with the same line as the smallest node. If it works in this way, my feature request will be invalid.

**Comment by David-Kunz** [comment]
Alright, no problem!
