### ISSUE TITLE
it's not work

### ISSUE THREAD

**Issue by ayoubelmhamdi** [David-Kunz/treesitter-unit#8]
I'm testing by my config `neovim` and with [mini.lua](https://gist.github.com/3d392fb17ccd23e7274a8784741e18a3)
```bash
$ nvim -u mini.lua
```
but nothing was selected

**Comment by David-Kunz** [comment]
Hi @ayoubelmhamdi ,

- Which programming language are you testing it with?
- Did you install treesitter for that language?

https://github.com/nvim-treesitter/nvim-treesitter

Thanks and best regards,
David

**Comment by ayoubelmhamdi** [comment]
it's work now, after the installation of treesittre language ^_^
thank you
